services:
  gses2022:
    container_name: gses2022
    build:
      context: .
      dockerfile: ./apps/gses2-app/Dockerfile
      target: development
    command: npm run start:dev gses2-app
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - rabbitmq
      - app-logger
  
  app-logger:
    container_name: app-logger
    build:
      context: .
      dockerfile: ./apps/app-logger/Dockerfile
      target: development
    command: npm run start:dev app-logger
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
  
  customer-app:
    container_name: customer-app
    build:
      context: .
      dockerfile: ./apps/customer-app/Dockerfile
      target: development
    command: npm run start:dev customer-app
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - postgres
  
  notification-app:
    container_name: notification-app
    build:
      context: .
      dockerfile: ./apps/notification-app/Dockerfile
      target: development
    command: npm run start:dev notification-app
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - postgres

  orchestrator-app:
    container_name: orchestrator-app
    build:
      context: .
      dockerfile: ./apps/orchestrator-app/Dockerfile
      target: development
    command: npm run start:dev orchestrator-app
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  docker-nest-postgres: