services:
  api:
    container_name: gses2022
    build:
     dockerfile: Dockerfile
     context: .
     target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local